import { describe, expect, it } from 'vitest'
import JSZip from 'jszip'
import { parseOdt } from '../src/parse'

/** A hand-authored content.xml resembling real LibreOffice Writer output (not generated by this package), so parse.ts is checked against independent ODF syntax rather than only its own generator's output. */
const CONTENT_XML = `<?xml version="1.0" encoding="UTF-8"?>
<office:document-content
  xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"
  xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0"
  xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0"
  xmlns:table="urn:oasis:names:tc:opendocument:xmlns:table:1.0"
  xmlns:draw="urn:oasis:names:tc:opendocument:xmlns:drawing:1.0"
  xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0"
  xmlns:xlink="http://www.w3.org/1999/xlink"
  office:version="1.2">
  <office:automatic-styles>
    <style:style style:name="P1" style:family="paragraph">
      <style:paragraph-properties fo:text-align="center"/>
    </style:style>
    <style:style style:name="T1" style:family="text">
      <style:text-properties fo:font-weight="bold" fo:font-size="16pt" fo:color="#FF0000"/>
    </style:style>
    <text:list-style style:name="L1">
      <text:list-level-style-number text:level="1"><style:list-level-properties/></text:list-level-style-number>
    </text:list-style>
    <text:list-style style:name="L2">
      <text:list-level-style-bullet text:level="1" text:bullet-char="•"/>
    </text:list-style>
  </office:automatic-styles>
  <office:body>
    <office:text>
      <text:h text:style-name="P1" text:outline-level="1"><text:span text:style-name="T1">Annual Report</text:span></text:h>
      <text:p>First paragraph hello odt</text:p>
      <text:list text:style-name="L2">
        <text:list-item><text:p>Bullet one</text:p></text:list-item>
        <text:list-item><text:p>Bullet two</text:p></text:list-item>
      </text:list>
      <text:list text:style-name="L1">
        <text:list-item><text:p>Step one</text:p></text:list-item>
      </text:list>
      <table:table>
        <table:table-row>
          <table:table-cell><text:p>Metric</text:p></table:table-cell>
          <table:table-cell><text:p>Value</text:p></table:table-cell>
        </table:table-row>
        <table:table-row>
          <table:table-cell><text:p>Revenue</text:p></table:table-cell>
          <table:table-cell><text:p>100</text:p></table:table-cell>
        </table:table-row>
      </table:table>
      <text:p><draw:frame text:anchor-type="paragraph" svg:width="4cm" svg:height="3cm">
        <draw:image xlink:href="Pictures/image1.png" xlink:type="simple" xlink:show="embed" xlink:actuate="onLoad"/>
      </draw:frame></text:p>
    </office:text>
  </office:body>
</office:document-content>`

async function buildFixture(): Promise<Uint8Array> {
  const zip = new JSZip()
  zip.file('mimetype', 'application/vnd.oasis.opendocument.text', { compression: 'STORE' })
  zip.file('content.xml', CONTENT_XML)
  zip.file('Pictures/image1.png', new Uint8Array([137, 80, 78, 71]))
  return zip.generateAsync({ type: 'uint8array' })
}

describe('parseOdt against hand-authored ODF XML', () => {
  it('reads a heading with centered alignment and a formatted run', async () => {
    const parsed = await parseOdt(await buildFixture())
    const heading = parsed.blocks[0]!
    expect(heading).toMatchObject({ type: 'heading', level: 1, format: { align: 'center' } })
    expect(heading.runs).toEqual([{ text: 'Annual Report', bold: true, sizeHalfPoints: 32, color: 'FF0000' }])
  })

  it('reads a plain paragraph', async () => {
    const parsed = await parseOdt(await buildFixture())
    expect(parsed.blocks[1]).toMatchObject({ type: 'paragraph' })
    expect(parsed.blocks[1]!.runs).toEqual([{ text: 'First paragraph hello odt' }])
  })

  it('classifies a bullet list-style as bullet and a number list-style as ordered', async () => {
    const parsed = await parseOdt(await buildFixture())
    const kinds = parsed.blocks
      .filter((b) => b.type === 'listItem')
      .map((b) => [b.list?.kind, b.runs?.[0]?.text])
    expect(kinds).toEqual([
      ['bullet', 'Bullet one'],
      ['bullet', 'Bullet two'],
      ['ordered', 'Step one'],
    ])
  })

  it('reads table cell text', async () => {
    const parsed = await parseOdt(await buildFixture())
    const table = parsed.blocks.find((b) => b.type === 'table')!
    expect(table.table!.rows).toEqual([
      [{ paras: ['Metric'] }, { paras: ['Value'] }],
      [{ paras: ['Revenue'] }, { paras: ['100'] }],
    ])
  })

  it('reads a paragraph-anchored image block and resolves its bytes to a data URL', async () => {
    const parsed = await parseOdt(await buildFixture())
    const image = parsed.blocks.find((b) => b.type === 'image')!
    expect(image.imageDataUrl).toMatch(/^data:image\/png;base64,/)
    expect(image.imageWidthPx).toBeGreaterThan(0)
  })

  it('rejects a non-text OpenDocument file with a clear error', async () => {
    const zip = new JSZip()
    zip.file('mimetype', 'application/vnd.oasis.opendocument.presentation', { compression: 'STORE' })
    zip.file('content.xml', '<?xml version="1.0"?><office:document-content/>')
    const bytes = await zip.generateAsync({ type: 'uint8array' })
    await expect(parseOdt(bytes)).rejects.toThrow(/not a text document/)
  })
})
