import { describe, expect, it } from 'vitest'
import JSZip from 'jszip'
import { parseOdp } from '../src/parse'

/** A hand-authored content.xml resembling real LibreOffice Impress output (not generated by this package), so parse.ts is checked against independent ODF syntax rather than only its own generator's output. */
const CONTENT_XML = `<?xml version="1.0" encoding="UTF-8"?>
<office:document-content
  xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"
  xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0"
  xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0"
  xmlns:draw="urn:oasis:names:tc:opendocument:xmlns:drawing:1.0"
  xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0"
  xmlns:svg="urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0"
  xmlns:xlink="http://www.w3.org/1999/xlink"
  xmlns:presentation="urn:oasis:names:tc:opendocument:xmlns:presentation:1.0"
  office:version="1.2">
  <office:automatic-styles>
    <style:style style:name="dp1" style:family="drawing-page">
      <style:drawing-page-properties draw:fill="solid" draw:fill-color="#FFFFCC"/>
    </style:style>
    <style:style style:name="gr1" style:family="graphic">
      <style:graphic-properties draw:fill="solid" draw:fill-color="#3366CC" draw:stroke="solid" svg:stroke-color="#000000" svg:stroke-width="0.05cm"/>
    </style:style>
    <style:style style:name="P1" style:family="paragraph">
      <style:paragraph-properties fo:text-align="center"/>
    </style:style>
    <style:style style:name="T1" style:family="text">
      <style:text-properties fo:font-weight="bold" fo:font-size="28pt" fo:color="#FFFFFF" style:font-name="Arial"/>
    </style:style>
    <style:style style:name="T2" style:family="text">
      <style:text-properties fo:font-style="italic" style:text-underline-style="solid"/>
    </style:style>
  </office:automatic-styles>
  <office:body>
    <office:presentation>
      <draw:page draw:name="page1" draw:style-name="dp1" draw:master-page-name="Default">
        <draw:frame draw:style-name="gr1" svg:x="2cm" svg:y="1.5cm" svg:width="10cm" svg:height="4cm">
          <draw:text-box>
            <text:p text:style-name="P1"><text:span text:style-name="T1">Title Slide</text:span></text:p>
            <text:p><text:span text:style-name="T2">subtitle text</text:span></text:p>
          </draw:text-box>
        </draw:frame>
        <draw:frame svg:x="1cm" svg:y="8cm" svg:width="4cm" svg:height="3cm">
          <draw:image xlink:href="Pictures/image1.png" xlink:type="simple" xlink:show="embed" xlink:actuate="onLoad"/>
        </draw:frame>
      </draw:page>
    </office:presentation>
  </office:body>
</office:document-content>`

const STYLES_XML = `<?xml version="1.0" encoding="UTF-8"?>
<office:document-styles xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"
  xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0"
  xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" office:version="1.2">
  <office:styles/>
  <office:automatic-styles>
    <style:page-layout style:name="PM1">
      <style:page-layout-properties fo:page-width="25.4cm" fo:page-height="19.05cm"/>
    </style:page-layout>
  </office:automatic-styles>
  <office:master-styles>
    <style:master-page style:name="Default" style:page-layout-name="PM1"/>
  </office:master-styles>
</office:document-styles>`

async function buildFixture(): Promise<Uint8Array> {
  const zip = new JSZip()
  zip.file('mimetype', 'application/vnd.oasis.opendocument.presentation', { compression: 'STORE' })
  zip.file('content.xml', CONTENT_XML)
  zip.file('styles.xml', STYLES_XML)
  zip.file('Pictures/image1.png', new Uint8Array([137, 80, 78, 71]))
  return zip.generateAsync({ type: 'uint8array' })
}

describe('parseOdp against hand-authored ODF XML', () => {
  it('reads slide size from styles.xml page-layout (4:3, cm)', async () => {
    const opened = await parseOdp(await buildFixture())
    // 25.4cm = 10in exactly; 19.05cm = 7.5in exactly — round numbers make the
    // unit conversion itself easy to verify by hand.
    expect(opened.deck.size.cx).toBe(9144000)
    expect(opened.deck.size.cy).toBe(6858000)
  })

  it('reads the page background from its drawing-page style', async () => {
    const opened = await parseOdp(await buildFixture())
    expect(opened.deck.slides[0]!.background).toEqual({ type: 'solid', color: '#FFFFCC' })
  })

  it('reads frame geometry (cm -> EMU) with no rotation', async () => {
    const opened = await parseOdp(await buildFixture())
    const title = opened.deck.slides[0]!.elements[0]!
    // 2cm/1.5cm/10cm/4cm at 360000 EMU/cm
    expect(title.transform).toEqual({
      offset: { x: 720000, y: 540000, cx: 3600000, cy: 1440000 },
      rot: 0,
      flipH: false,
      flipV: false,
    })
  })

  it('reads graphic fill/stroke from the referenced style', async () => {
    const opened = await parseOdp(await buildFixture())
    const title = opened.deck.slides[0]!.elements[0]!
    if (title.type !== 'text') throw new Error('expected text')
    expect(title.fill).toEqual({ type: 'solid', color: '#3366CC' })
    expect(title.stroke).toEqual({ fill: { type: 'solid', color: '#000000' }, width: 18000 })
  })

  it('reads paragraph alignment and run character formatting from styles', async () => {
    const opened = await parseOdp(await buildFixture())
    const title = opened.deck.slides[0]!.elements[0]!
    if (title.type !== 'text') throw new Error('expected text')
    const [p1, p2] = title.text!.paragraphs
    expect(p1!.align).toBe('center')
    expect(p1!.runs).toEqual([
      { text: 'Title Slide', bold: true, fontSize: 28, color: '#FFFFFF', fontFamily: 'Arial' },
    ])
    expect(p2!.align).toBeUndefined()
    expect(p2!.runs).toEqual([{ text: 'subtitle text', italic: true, underline: true }])
  })

  it('reads a picture frame\'s media reference and resolves its bytes via the archive', async () => {
    const opened = await parseOdp(await buildFixture())
    const pic = opened.deck.slides[0]!.elements[1]!
    expect(pic.type).toBe('picture')
    if (pic.type !== 'picture') throw new Error('expected picture')
    expect(pic.mediaRef).toBe('Pictures/image1.png')
    expect(opened.archive.readBytes(pic.mediaRef)).toEqual(new Uint8Array([137, 80, 78, 71]))
  })
})
